### ISSUE TITLE
Run the application locally

### ISSUE THREAD

**Issue by mitcha95** [sbkwgh/forum#18]
Hello, 
when typing "npm run app" some errors appear, i installed latest versions of npm & vue

here s the log file
[2019-04-19T15_28_11_600Z-debug.log](https://github.com/sbkwgh/forum/files/3098621/2019-04-19T15_28_11_600Z-debug.log)

there s some missing features i think, how to fix them!
thanks

**Comment by sbkwgh** [comment]
For either the frontend or the server it should be `npm run dev` not `npm run app`

**Comment by mitcha95** [comment]
oh yess sryy here s screenshot from cmd
![issue](https://user-images.githubusercontent.com/48943328/56432414-8a52a300-62cd-11e9-91fa-ac6c26e61dab.PNG)

and the log file
[2019-04-19T16_03_11_810Z-debug.log](https://github.com/sbkwgh/forum/files/3098629/2019-04-19T16_03_11_810Z-debug.log)

srry i am novice with vue

**Comment by sbkwgh** [comment]
Have you done `npm install`?

**Comment by sbkwgh** [comment]
Did this solve your issue? Will close this issue
