### ISSUE TITLE
Failed to npm run build in frontend using node.js 10 or later

### ISSUE THREAD

**Issue by mzch** [sbkwgh/forum#22]
Hi,
`npm run build` is failed in `frontend` by using node.js 10.17.0 or later.
```
> frontend@1.0.0 build /srv/vueforum/forum/frontend
> node build/build.js

⠧ building for production...cosmiconfig requires at least version 4 of Node, please upgrade
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/vueforum/.npm/_logs/2019-11-10T17_44_50_132Z-debug.log
```

But when I use 8.16.2, `npm run build` is also failed.
```
ERROR in ./~/css-loader?{"minimize":true,"sourceMap":true}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-25441132","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: Error: Missing binding /srv/vueforum/forum/frontend/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x
```

Any idea?

**Comment by sastava007** [comment]
@sbkwgh What version of Node, you used to build this project?
Was it <4..?

**Comment by mzch** [comment]
Sorry, objects compiled by 10.x remained. I tried fresh install by 8.x and got successful.

**Comment by sastava007** [comment]
@mzch Can you tell the exact version number?

**Comment by mzch** [comment]
Hi @sastava007 ,
```
vueforum@la:~$ node -v
v8.16.2
vueforum@la:~$ npm -v
6.4.1
```

**Comment by sastava007** [comment]
I'm able to run frontend using node@10.17.0 but when I'm running backend it's giving error.
Can you suggest any way to fix it.
Actually I'm not using original repo, but the one modified by @marcelobbfonseca. He has made some changes in the original code and hance able to run using node@10, but stuck with backend.

![image](https://user-images.githubusercontent.com/43990819/70390686-472b7880-19f3-11ea-8cff-715fbc6f9a9e.png)

**Comment by mzch** [comment]
Do you see my another issue, #23? This app seems to mix capitalized column name and lower-cased column name, so it's unable to fetch db-data correctly.

**Comment by sastava007** [comment]
@mzch Have you tried yourself changing those columns name?
I mean converting them in same case?

**Comment by sastava007** [comment]
@mzch If adding `lower_case_table_names = 1` fixes this problem?

**Comment by mzch** [comment]
Yes. At least my instance runs correctly by adding it.

**Comment by sastava007** [comment]
Where we need to add it?
I mean in which file
@mzch

**Comment by mzch** [comment]
I added it to `my.cnf` at `[mysqld]` section.

**Comment by sastava007** [comment]
@mzch Not able to find this file, in which directory it is located or have you created this by your own?

**Comment by mzch** [comment]
In most cases, it places at `/etc/mysql` or in case of mariadb you can create .cnf file, i.e. server.cnf in `/etc/mysql/mariadb.conf.d` as below:

```
[mysqld]
lower_case_table_names  = 1
```
