### ISSUE TITLE
Can't run Vue after build

### ISSUE THREAD

**Issue by urosvgd** [sbkwgh/forum#26]
Node seems like it can't run these files.
Refused to apply style from '<domain>/css/app.f824e728.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Same applies for js files (app.<number>.js, and chunk-vendros.<numbers>.js).

Don't know much about Vue, do you have any idea ?

**Comment by sumarsanaadi** [comment]
how you solved this problem ? @urosvgd

**Comment by urosvgd** [comment]
I think the problem lies in server.js, try to correct  piece of code that serves static files. If that does not work for you I will try to replicate problem.

**Comment by sumarsanaadi** [comment]
Hi Uros Jovicic,

Thank you for your suggestion, my problem fixed after use this code  app.use
(express.static('frontend/dist/'));

Best Regards
