### ISSUE TITLE
Demo showing error, deploying to Heroku shows different error

### ISSUE THREAD

**Issue by melaniedeleeuw** [sbkwgh/forum#30]
Hi!

I really like your vue-forum and have been trying this past week to get a personal version up and running. Unfortunately, I have not succeeded due to the following two issues:

1. The current demo shows the following error:
![image](https://user-images.githubusercontent.com/66666873/84364012-d2b6d980-abcf-11ea-966f-04234893e5ba.png)

2. When following all the steps to install the project on Heroku, with ClearDB as a DB add-on for Heroku, I get the following errors in de devtools with a blank page:
![image](https://user-images.githubusercontent.com/66666873/84364374-4658e680-abd0-11ea-925a-f42d91e001b6.png)

The errors specify that text/html are the wrong MIME types for .js and .css files which can be found in the dist.

My build is successful, I've installed all dependencies and get a positive response in my terminal. I think I am doing something wrong, but am not sure what.

My questions:
- Is the demo and thus the current project version still a workable version?
- Is there a step missing from the Heroku deployment or a build rule missing in the project?

Hope you can help me! If you need more info, I am happy to provide!

Regards,
Melanie

**Comment by sbkwgh** [comment]
Hi Melanie

I’m currently quite busy but am committed to getting this project up again over the next week(s)! I will have a look at your issue – but in the meantime, the demo page is erroring just because the free database I’ve used has no more memory left.

Best

**Comment by sbkwgh** [comment]
Hi please try again with the latest version !

**Comment by melaniedeleeuw** [comment]
> Hi please try again with the latest version !

**Comment by melaniedeleeuw** [comment]
Hi!

Thanks, the demo works, so now I know that there is something I have to figure out on my side. Thank you for your quick reply.

Regards

**Comment by sbkwgh** [comment]
It should be enough to git pull from this repository and push the latest version to heroku. Let me know if this doesn't work

**Comment by melaniedeleeuw** [comment]
It absolutely was! I've gotten it up and running now and it is supercool. Thanks!!
