### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by tiendungdev** [sbkwgh/forum#9]
I tried installing hundreds of times, but failed. so sad

**Comment by sbkwgh** [comment]
What sort of errors are you getting?

**Comment by tiendungdev** [comment]
Many errors,

Can't `npm install ` and `npm run build`

https://imgur.com/a/a8Vkght

**Comment by sbkwgh** [comment]
It says you haven't got a new enough version of node (at least v4).

Try installing the latest node version and then follow these instructions for node gyp: https://github.com/nodejs/node-gyp#option-1

**Comment by tiendungdev** [comment]
I really run `npm install --global --production windows-build-tools` but can't

**Comment by sbkwgh** [comment]
Are you running power shell as an administrator?

**Comment by tiendungdev** [comment]
Yes, I run as an administrator

**Comment by sbkwgh** [comment]
What are the errors when you run that command then?

**Comment by tiendungdev** [comment]
When run `npm install`

https://imgur.com/a/NN5fRgT
